[package]
name = "transformer-rs"
version = "0.1.0"
edition = "2018"


[dependencies]
serde_json = "1.0.66"
serde = { version = "1.0.127", features = ["derive"] }
serde-value = "0.7.0"
rayon = "^1.5.1"
env_logger = "0.9.0"
log = "0.4"
once_cell = "1.8.0"
anyhow = "1.0.44"